### ISSUE TITLE
pod name are overlapping

### ISSUE THREAD

**Issue by utix** [Trois-Six/k8s-diagrams#6]
![image](https://user-images.githubusercontent.com/245365/116622619-49bea300-a945-11eb-8da2-06220452a48c.png)

Perhaps the pod name can be shorten as the rs contains the beginning of the name

For example with:
ms-ext-resources-web-5bdd575f7d
ms-ext-resources-web-5bdd575f7d-4hf5d

ms-ext-resources-web-5bdd575f7d
ms-.ext..-4hf5d

**Comment by trois-six** [comment]
Please try https://github.com/Trois-Six/k8s-diagrams/releases/tag/v0.0.6. Example https://github.com/Trois-Six/k8s-diagrams/blob/main/big_diagram.png.

**Comment by utix** [comment]
fixed
![image](https://user-images.githubusercontent.com/245365/116694216-4b2cb180-a9bf-11eb-9b27-7d61a882ff16.png)
